# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: pt

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: word
    stop_words:
     - a
     - agora
     - ainda
     - alguém
     - algum
     - antes
     - ao
     - após
     - aquela
     - aquele
     - aquilo
     - as
     - até
     - através
     - cada
     - coisa
     - com
     - como
     - contra
     - contudo
     - da
     - daquele
     - de
     - dele
     - depois
     - desse
     - desta
     - deve
     - disse
     - disso
     - diz
     - do
     - dos
     - e
     - ela
     - ele
     - eles
     - em
     - enquanto
     - entre
     - era
     - eram
     - éramos
     - essa
     - essas
     - esse
     - esses
     - esta
     - estamos
     - estão
     - estas
     - estava
     - estavam
     - estávamos
     - este
     - esteja
     - estejam
     - estes
     - esteve
     - estive
     - estivemos
     - estiver
     - estiveram
     - estiverem
     - estivermos
     - estivesse
     - estivéssemos
     - estou
     - eu
     - fazendo
     - fazer
     - feita
     - feitas
     - feito
     - feitos
     - foi
     - fomos
     - for
     - fora
     - foram
     - forem
     - formos
     - fosse
     - fossem
     - fôssemos
     - fui
     - grande
     - há
     - haja
     - hajam
     - hão
     - havemos
     - havia
     - hei
     - houve
     - houver
     - houvera
     - houveram
     - houverem
     - houvesse
     - isso
     - isto
     - já
     - la
     - lá
     - lhe
     - lhes
     - mais
     - mas
     - me
     - mesma
     - mesmas
     - mesmo
     - mesmos
     - meu
     - meus
     - minha
     - minhas
     - muita
     - muitas
     - muito
     - muitos
     - na
     - não
     - nas
     - nem
     - nenhum
     - nessa
     - nessas
     - nesta
     - nestas
     - ninguém
     - nos
     - nós
     - nossa
     - nossas
     - nosso
     - nossos
     - num
     - numa
     - nunca
     - o
     - os
     - ou
     - outra
     - outras
     - outro
     - outros
     - para
     - pela
     - pelas
     - pelo
     - pelos
     - pequena
     - pequenas
     - pequeno
     - pequenos
     - perante
     - pode
     - podendo
     - poder
     - poderia
     - poderiam
     - podia
     - podiam
     - pois
     - por
     - porém
     - porque
     - posso
     - pouca
     - poucas
     - pouco
     - poucos
     - primeiro
     - primeiros
     - própria
     - próprias
     - próprio
     - próprios
     - pude
     - quais
     - qual
     - quando
     - quanto
     - quantos
     - que
     - quem
     - são
     - se
     - seja
     - sejam
     - sejamos
     - sem
     - sempre
     - sendo
     - ser
     - será
     - serão
     - serei
     - seremos
     - seria
     - seriam
     - seríamos
     - seu
     - seus
     - sido
     - só
     - sob
     - sobre
     - somos
     - sou
     - sua
     - suas
     - talvez
     - também
     - tampouco
     - te
     - tem
     - temos
     - tenha
     - tenham
     - tenhamos
     - tenho
     - ter
     - terá
     - terão
     - terei
     - teremos
     - teria
     - teriam
     - teríamos
     - teu
     - teus
     - teve
     - ti
     - tido
     - tinha
     - tive
     - tivesse
     - todos
     - tudo
     - última
     - último
     - um
     - uma
     - vendo
     - ver
     - vez
     - vindo
     - vir
     - você
  - name: DIETClassifier
    epochs: 100
    model_confidence: softmax
    constrain_similarities: True
  - name: EntitySynonymMapper
  - name: ResponseSelector
    model_confidence: softmax
    epochs: 100
    constrain_similarities: True
  - name: FallbackClassifier
    threshold: 0.60
    ambiguity_threshold: 0.1

policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: RulePolicy
#   - name: UnexpecTEDIntentPolicy
#     max_history: 5
#     epochs: 100
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true
